### ISSUE TITLE
Can you provide more freeze information

### ISSUE THREAD

**Issue by xiaoyao9184** [Shainny/DomoticzXiaomiPlugins#1]
Hi
I fork your project, and develop on windows, 
and no freeze domoticz's plugin system at all.
but when i deploy it on raspberry,
it freeze, stop call plugin's `on` callback, 
but will still execute the `import` statement and `def` statement.

https://github.com/xiaoyao9184/DomoticzXiaomiPlugins/blob/ecb06cade90a5499f45476d2c0a81e8cba7330b8/MiioChuangmiPlug/plugin.py#L43

when i move the `import miio` statement inside the onStart function, it won't freeze.

Is this consistent with your phenomenon?

**Comment by xiaoyao9184** [comment]
Ok, i think domoticz fix it in beta version 4.10

**Comment by Shainny** [comment]
Thanks for your review.
I was waiting for Domoticz to fix this, or include the mio plugin themselves.
I'll get back to it when I have time.
